# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-01 21:21
from __future__ import unicode_literals

import autoslug.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pjapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('annotations', models.TextField(blank=True, help_text='Your annotations will only be seen by you', verbose_name='My annotations (private)')),
            ],
            options={
                'ordering': ['date_created'],
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('content', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('public', models.BooleanField(db_index=True, default=False)),
                ('activity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='pjapp.Activity')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='CustomActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Activity', max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Custom activities',
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('annotations', models.TextField(blank=True, help_text='Your annotations will only be seen by you', verbose_name='My annotations (private)')),
                ('listed_publicly', models.BooleanField(default=False, help_text="If checked, it will appear on the app's directory. If unchecked, trajectory will be accessible to users who have the URL")),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from=pjapp.models.make_slug, unique=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='PathLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('from_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forward_links', to='pjapp.Activity')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pjapp.Path')),
                ('to_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backward_links', to='pjapp.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='PathPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_position_x', models.PositiveSmallIntegerField(db_index=True, default=0, null=True)),
                ('block_position_y', models.PositiveSmallIntegerField(db_index=True, default=0, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='pjapp.Activity')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='pjapp.Path')),
            ],
            options={
                'ordering': ['block_position_y', 'block_position_x'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('annotations', models.TextField(blank=True, help_text='Your annotations will only be seen by you', verbose_name='My annotations (private)')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='RecordedPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_started', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_ended', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_instances', to='pjapp.Path')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_started'],
            },
        ),
        migrations.CreateModel(
            name='RecordedStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'In progress'), ('S', 'Skipped'), ('D', 'Done')], db_index=True, default='P', max_length=1)),
                ('date_started', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_ended', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('path_index', models.PositiveSmallIntegerField(default=0)),
                ('is_canonical', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pjapp.Activity')),
                ('custom_activity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pjapp.CustomActivity')),
                ('next_step', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_step', to='pjapp.RecordedStep')),
                ('recorded_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pjapp.RecordedPath')),
            ],
            options={
                'ordering': ['recorded_path', 'path_index'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, to='pjapp.Tag'),
        ),
        migrations.AddField(
            model_name='path',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='pjapp.Project'),
        ),
        migrations.AddField(
            model_name='path',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, to='pjapp.Tag'),
        ),
        migrations.AddField(
            model_name='customactivity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pjapp.Project'),
        ),
        migrations.AddField(
            model_name='customactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='custom_activity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='pjapp.CustomActivity'),
        ),
        migrations.AddField(
            model_name='comment',
            name='recorded_path',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='pjapp.RecordedPath'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='pjapp.Project'),
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, to='pjapp.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='pathlink',
            unique_together=set([('path', 'from_activity', 'to_activity')]),
        ),
    ]
